# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: radar.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bradar.proto\"T\n\x08ObjLocus\x12\x10\n\x08\x64\x65viceSn\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\r\x12\x19\n\tlocusList\x18\x04 \x03(\x0b\x32\x06.Locus\"\x94\x03\n\x05Locus\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07objType\x18\x02 \x01(\r\x12\x0c\n\x04lane\x18\x03 \x01(\r\x12\x0e\n\x06length\x18\x04 \x01(\x02\x12\r\n\x05width\x18\x05 \x01(\x02\x12\x0e\n\x06height\x18\x06 \x01(\x02\x12\x11\n\tmeasState\x18\x07 \x01(\r\x12\x0c\n\x04posX\x18\x08 \x01(\x02\x12\x0c\n\x04posY\x18\t \x01(\x02\x12\x0c\n\x04posZ\x18\n \x01(\x02\x12\x10\n\x08latitude\x18\x0b \x01(\x01\x12\x11\n\tlongitude\x18\x0c \x01(\x01\x12\x10\n\x08\x61ltitude\x18\r \x01(\x01\x12\r\n\x05speed\x18\x0e \x01(\x02\x12\x12\n\naccelerate\x18\x0f \x01(\x02\x12\x0f\n\x07\x61zimuth\x18\x10 \x01(\x02\x12\x13\n\x0bprobability\x18\x11 \x01(\r\x12\x11\n\teventMask\x18\x12 \x01(\r\x12\x13\n\x0bvehicleType\x18\x13 \x01(\r\x12\x14\n\x0cvehicleColor\x18\x14 \x01(\r\x12\x11\n\tplateType\x18\x15 \x01(\r\x12\x12\n\nplateColor\x18\x16 \x01(\r\x12\x0f\n\x07plateNo\x18\x17 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'radar_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OBJLOCUS']._serialized_start=15
  _globals['_OBJLOCUS']._serialized_end=99
  _globals['_LOCUS']._serialized_start=102
  _globals['_LOCUS']._serialized_end=506
# @@protoc_insertion_point(module_scope)
